Milestone 4
JayKowski/calculator pull request #4
Opened 2020-09-24 17:26 UTC by JayKowski

-Added requested logic control features. Ready for review

2020-09-24 21:11 UTC, Forison requested changes
## Status:: Changes required❌
# 🙋‍♂️ @JayKowski 
#### You have done a good job on this one so far, however, there are a few issues we have to address to get his project approved👨.
* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ]  Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
- Check my comment below👇.
### That is it, kindly make the change and submit a re-review👨‍🔧
#### Happy coding👨‍💻 
Addo Forison

2020-09-24 21:11 UTC, Forison commented on src/logic/calculate.js
> +/* eslint-disable */
do not disable linter else you miss the key learning objective.

2020-09-24 21:11 UTC, Forison commented on src/logic/operate.js
> +/* eslint-disable */
do not disable linter else you miss the key learning objective.

2020-09-24 21:11 UTC, Forison commented on src/logic/operate.js
> +  let res = 0;
**[OPTIONAL]**
We could wrap `numberOne` and `numberTwo` in big.js and store them in a new variable one time. So we can keep calling them in the various conditional block.

2020-09-26 22:06 UTC, shloch approved these changes
## Hello @JayKowski 

Great job with bringing the corrections above
![accomplished](https://user-images.githubusercontent.com/40712459/94351072-dbcb9980-004c-11eb-88b0-d267ad9a3abd.jpg)

We're ready for the next milestone
Keep up with the good work
Happy coding

2020-09-26 22:06 UTC, shloch commented on src/logic/operate.js
> +    res = (fNum / sNum).toString();
dont forget to manage DIVISION BY ZERO error on the next milestone, else it will generate an error

2020-09-27 22:03 UTC, merged